config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  root to: "quizz#home"

  %w(quizz
     show).each do |page|
    get page, to: "quizz##{page}", as: page
  end

  resources :categories
  resources :questions
  resources :teams
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :questions

  NAME = %w(history geography art literature comics movie music culture religion mithology sport technology science politics).freeze

  validates :name, presence: true
end

app/models/category/name.rb
class Category
  class Name

    def initialize(key)
      @key = key
    end

    def human_name
      I18n.t("models.category.name.#{@key}")
    end

  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :category

  has_attachment :image, accept: [:gif, :jpg, :jpeg, :png]

  validates :question_name, presence: true
  validates :answer, presence: true
  validates :image, presence: true
end

app/models/team.rb
class Team < ActiveRecord::Base

  validates :name, presence: true

  def sum_points
    game1 + game2 + game3 + game4 + game5 + game6 + game7 + game8 + game9 + game10 + game11 + game12 + game13 + game14 + game15
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_admin!

  def toast(type, text)
    flash[:toast] = { type => text }
  end

  private

  def authenticate_admin!
    authenticate_or_request_with_http_basic do |username, password|
      expected_username = ENV.fetch("APP_USERNAME")
      expected_password = ENV.fetch("APP_PASSWORD")
      username == expected_username && password == expected_password
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all.page(params[:page]).per_page(15)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path, notice: "Kategorija uspješno kreirana!"
    else
      render "new"
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to categories_path, notice: "Izmjene uspješno spremljene!"
    else
      render "edit"
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_path, notice: "Kategorija izbrisana!"
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all.page(params[:page]).per_page(15)
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to questions_path, notice: "Pitanje uspješno kreirano!"
    else
      render "new"
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to questions_path, notice: "Izmjene uspješno spremljene!"
    else
      render "edit"
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    redirect_to questions_path, notice: "Pitanje izbrisano!"
  end

  private

  def question_params
    params.require(:question).permit(:question_name, :answer, :image, :category_id)
  end

end

app/controllers/quizz_controller.rb
class QuizzController < ApplicationController

  def home
  end

  def quizz
    @categories = Category.all
    @questions = Question.all
  end

  def show
    @question = Question.find_by_id(params[:question_id])
    @category = @question.category
    @teams = Team.all.order("created_at DESC")
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @teams = Team.all
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)

    if @team.save
      redirect_to teams_path, notice: "Ekipa uspješno dodana!"
    else
      render "new"
    end
  end

  def edit
    @team = Team.find(params[:id])
  end

  def update
    @team = Team.find(params[:id])
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to(teams_path, notice: "Izmjene uspješno spremljene!") }
      else
        format.html { render "edit" }
      end
    end
  end

  def destroy
    @team = Team.find(params[:id])
    @team.destroy

    redirect_to teams_path, notice: "Ekipa izbrisana!"
  end

  private

  def team_params
    params.require(:team).permit(:name, :game1, :game2, :game3, :game4, :game5, :game6, :game7, :game8, :game9, :game10, :game11, :game12,
                                 :game13, :game14, :game15)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def main_menu_items
    [
      ["Početna", root_path],
      ["Započni kviz", quizz_path]
    ]
  end

  def render_main_menu
    items = main_menu_items
    return "" if items.empty?
    lis = items.map do |item|
      li_class = current_page?(item[1]) ? "active" : nil
      link = link_to(item[0], item[1])
      content_tag(:li, link, class: li_class)
    end
    content_tag(:ul, lis.join("").html_safe, class: "right")
  end

  def side_menu_items
    [
      ["Uhvaćeni u neznanju!"],
      ["Kategorije", categories_path],
      ["Pitanja", questions_path],
      ["Ekipe", teams_path],
      ["Dodaj kategoriju", new_category_path],
      ["Dodaj pitanje", new_question_path],
      ["Dodaj ekipu", new_team_path]
    ]
  end

  def render_side_menu
    items = side_menu_items
    return "" if items.empty?
    lis = items.map do |item|
      li_class = current_page?(item[1]) ? "active" : nil
      link = link_to(item[0], item[1])
      content_tag(:li, link, class: li_class)
    end
    content_tag(:ul, lis.join("").html_safe, id: "slide-out", class: "side-nav")
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/for_select_helper.rb
module ForSelectHelper

  def categories_for_select
    Category::NAME.map { |key| [Category::Name.new(key).human_name, key] }
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  QUESTION_IMAGE_OPTIONS = {
    small: { width: 20, height: 20 },
    medium: { width: 300, height: 400 },
    large: { width: 450, height: 550 }
  }.freeze

  def question_image_tag(question, size)
    image_path = question_image_path(question, size)
    options = QUESTION_IMAGE_OPTIONS[size]
    cl_image_tag(image_path, options)
  end

  def question_image_path(question, size)
    if question.image.present?
      question.image.path
    else
      asset_path("question/fallback/#{size}.png")
    end
  end
end

app/helpers/quizz_helper.rb
module QuizzHelper
  def md_to_html(text)
    options = {
      filter_html: false,
      fenced_code_blocks: true,
      gh_blockcode: true,
      hard_wrap: true
    }
    extensions = {
      autolink: true,
      no_intra_emphasis: true
    }
    renderer = Redcarpet::Render::HTML.new(options)
    md_for_html = Redcarpet::Markdown.new(renderer, extensions)
    md_for_html.render(text).html_safe
  end
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/categories/_form.html.erb
<%= f.input :name %>

app/views/categories/edit.html.erb
<% provide(:title, "Uredi kategoriju") %>

<div class="create-wrapper">
  <div class="card-panel hoverable">
    <h1>Uredi kategoriju</h1>

    <%= simple_form_for @category do |f| %>
      <%= render "form", f: f %>
      <%= f.button :button, "Spremi Izmjene" %>
    <% end %>
  </div>
</div>

app/views/categories/index.html.erb
<% provide(:title, "Kategorije") %>

<div class="create-wrapper">
  <div class="card-panel hoverable">
    <h1>Kategorije</h1>
    <%= link_to "Dodaj kategoriju", new_category_path, class: "waves-effect waves-light btn button1" %>
    <table class="highlight bordered">
      <thead>
        <tr>
          <th>Id</th>
          <th>Naziv kategorije</th>
          <th>Obriši</th>
        </tr>
      </thead>
      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= category.id %></td>
            <td><%= category.name %></td>
            <td><%= link_to category_path(category), method: :delete, data: { confirm: "Jeste li sigurni?" }, class: "delete" do %>
              <i class="material-icons">delete</i>
            <% end %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= will_paginate @categories %>

</div>
</div>

app/views/categories/new.html.erb
<% provide(:title, "Nova kategorija") %>

<div class="create-wrapper">
  <div class="card-panel hoverable">
    <h1>Dodaj novu kategoriju</h1>

    <%= simple_form_for @category do |f| %>
      <%= render "form", f: f %>
      <%= f.button :button, "Dodaj Kategoriju" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kviz | <%= yield(:title) %></title>
    <%= favicon_link_tag 'favicon.png' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= cloudinary_js_config %>

    <link href='https://fonts.googleapis.com/css?family=Ubuntu:400,500,700,500italic,700italic,300italic,400italic&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Butcherman&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

  </head>
  <body>
    <nav class="teal">
    <div class="nav-wrapper">
      <a href="#" data-activates="slide-out" class="button-collapse show-on-large"><i class="material-icons">reorder</i></a>
      <h1><%= link_to "Uhvaćeni u neznanju!", root_path, class: "brand-logo" %></h1>
      <%= render_main_menu %>
      <%= render_side_menu %>
    </div>
    </nav>


    <% if notice %>
      <script type="text/javascript">
        Materialize.toast('<%= notice %>', 4000)
        </script>
      <% end %>
      <% if alert %>
        <script type="text/javascript">
          Materialize.toast('<%= alert %>', 4000)
          </script>
        <% end %>

    <%= yield %>

    <%= javascript_include_tag "header" %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= f.collection_select(:category_id, Category.all, :id, :name, prompt: "Odaberi kategoriju") %>
<%= f.input :question_name, wrapper: :vertical_text_input, as: :text %>
<%= link_to "Markdown help", "http://assemble.io/docs/Cheatsheet-Markdown.html", target: "_blank", class: "right" %>
<%= f.input :answer %>
<%= f.input :image, as: :attachinary %>

app/views/questions/edit.html.erb
<% provide(:title, "Uredi pitanje") %>

<div class="create-wrapper">
  <div class="card-panel hoverable">
    <h1>Uredi pitanje</h1>

    <%= simple_form_for @question do |f| %>
      <%= render "form", f: f %>
      <%= f.button :button, "Spremi Izmjene" %>
    <% end %>
  </div>
</div>
<%= javascript_include_tag "form" %>

app/views/questions/index.html.erb
<% provide(:title, "Pitanja") %>

<div class="create-wrapper">
  <div class="card-panel hoverable">
    <h1>Pitanja</h1>
    <%= link_to "Dodaj pitanje", new_question_path, class: "waves-effect waves-light btn button1" %>
    <table class="highlight bordered">
      <thead>
        <tr>
          <th>Id</th>
          <th>Kategorija</th>
          <th>Slika</th>
          <th>Pitanje</th>
          <th>Odgovor</th>
          <th>Obriši</th>
        </tr>
      </thead>
      <tbody>
        <% @questions.each do |question| %>
          <tr>
            <td><%= question.id %></td>
            <td><%= question.category.name if question.category %></td>
            <td><%= question_image_tag(question, :small) %></td>
            <td><%= link_to truncate(question.question_name, length: 50), edit_question_path(question) %></td>
            <td><%= truncate(question.answer, length: 10) %></td>
            <td><%= link_to question_path(question), method: :delete, data: { confirm: "Jeste li sigurni?" }, class: "delete" do %>
              <i class="material-icons">delete</i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= will_paginate @questions %>

  </div>
</div>

app/views/questions/new.html.erb
<% provide(:title, "Novo pitanje") %>

<div class="create-wrapper">
  <div class="card-panel hoverable">
    <h1>Dodaj novo pitanje</h1>

    <%= simple_form_for @question do |f| %>
      <%= render "form", f: f %>
      <%= f.button :button, "Dodaj Pitanje" %>
    <% end %>
  </div>
</div>
<%= javascript_include_tag "form" %>

app/views/questions/quizz.html.erb
<div class="quizz">
  <%= image_tag("question.gif", alt: "question", class: "back-image") %>
  <div class="quizz-content">
    <% @categories.each do |category| %>
      <div id=<%= "box#{category.id}" -%>>
        <h1><%= category.name %></h1>
        <% category.questions.each_with_index do |question, i| %>
          <ul class="question-list" style="display: inline;">
           <li><%= link_to (i + 1), question(category_id: category.id, question_id: question.id) %></li>
          </ul>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/quizz/_teams_modal.html.erb
<div id="modal1" class="modal modal-fixed-footer">
  <div class="modal-content">
    <h4>Bodovanje | Poredak ekipa</h4>
    <table class="highlight bordered">
      <thead>
        <tr>
          <td>Naziv ekipe</td>
          <td>1. Krug</td>
          <td>2. Krug</td>
          <td>3. Krug</td>
          <td>4. Krug</td>
          <td>5. Krug</td>
          <td>6. Krug</td>
          <td>7. Krug</td>
          <td>8. Krug</td>
          <td>9. Krug</td>
          <td>10. Krug</td>
          <td>11. Krug</td>
          <td>12. Krug</td>
          <td>13. Krug</td>
          <td>14. Krug</td>
          <td>15. Krug</td>
          <td>ZBROJ BODOVA</td>
        </tr>
      </thead>
      <tbody>
        <% @teams.each do |team| %>
          <tr>
            <td class="team-text"><%= team.name %></td>
            <td><%= best_in_place team, :game1, as: :input %></td>
            <td><%= best_in_place team, :game2, as: :input %></td>
            <td><%= best_in_place team, :game3, as: :input %></td>
            <td><%= best_in_place team, :game4, as: :input %></td>
            <td><%= best_in_place team, :game5, as: :input %></td>
            <td><%= best_in_place team, :game6, as: :input %></td>
            <td><%= best_in_place team, :game7, as: :input %></td>
            <td><%= best_in_place team, :game8, as: :input %></td>
            <td><%= best_in_place team, :game9, as: :input %></td>
            <td><%= best_in_place team, :game10, as: :input %></td>
            <td><%= best_in_place team, :game11, as: :input %></td>
            <td><%= best_in_place team, :game12, as: :input %></td>
            <td><%= best_in_place team, :game13, as: :input %></td>
            <td><%= best_in_place team, :game14, as: :input %></td>
            <td><%= best_in_place team, :game15, as: :input %></td>
            <td class="team-text"><%= team.sum_points %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="modal-footer">
    <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Zatvori</a>
  </div>
</div>

app/views/quizz/home.html.erb
<% provide(:title, "Uhvaćeni u neznanju!") %>

<div class="home">
  <div id="background" class="home-wrapper center-align">
    <%= link_to quizz_path, class: "btn-floating btn-large waves-effect waves-light red" do %>
      <i class="material-icons">play_arrow</i>
    <% end %>
    <%= image_tag("hand_kviz.png", class: "home-logo") %>
  </div>
  <div class="logo-title">
    <h1>Uhvaćeni u neznanju!</h1>
    <% link_to "Započni kviz", quizz_path, class: "btn" %>
  </div>
</div>

app/views/quizz/quizz.html.erb
<% provide(:title, "Odaberi kategoriju i pitanje") %>

<div class="quizz">
  <%= image_tag("questionmark.png", alt: "question", class: "back-image") %>
  <div class="quizz-content">
    <div class="card-panel hoverable">
      <% @categories.each do |category| %>
        <div id=<%= "box#{category.id}" -%>>
          <h1><%= category.name %></h1>
          <% category.questions.each_with_index do |question, i| %>
            <ul class="question-list" style="display: inline;">
              <li><%= link_to (i + 1), show_path(question_id: question.id) %></li>
            </ul>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/quizz/show.html.erb
<% provide(:title, "Odgovori na pitanje!") %>

<%= render "quizz/teams_modal" %>

<div class="question">
  <%= image_tag("show.png", alt: "question", class: "question-image") %>
  <div class="question-wrapper">
    <div class="card-panel hoverable">
      <a class="btn-floating btn-large waves-effect waves-light red modal-trigger" href="#modal1"><i class="material-icons">add</i></a>
      <h1><%= @category.name %></h1>
      <div class="row">
        <div class="col s6">
          <div class="image left-align">
            <%= question_image_tag(@question, :large) %>
          </div>
        </div>
        <div class="col s6">
          <div class="question-text">
            <%= md_to_html @question.question_name %>
          </div>
        </div>
      </div>
      <p class="answer"><%= @question.answer %></p>
      <a id="show" class="waves-effect waves-light btn button1">Prikaži rješenje</a>
    </div>
  </div>
</div>
<%= javascript_include_tag "show" %>